### ISSUE TITLE
Development Roadmap (2024 Q4)

### ISSUE THREAD

**Issue by Ying1123** [sgl-project/sglang#1487]
Here is the development roadmap for 2024 Q4. Contributions and feedback are welcome ([**Join Bi-weekly Development Meeting**](https://t.co/4BFjCLnVHq)). Previous 2024 Q3 roadmap can be found in #634.

## Performance
- [x] Hide CPU overhead with overlapped scheduler (#1738, #2067)
- [ ] Support speculative decoding
  - Eagle  #2150 
  - Reference-based. #270
  - Medusa head #859
  - Draft model based.
- [x] Sparse Attention #1459
- [x] Faster grammar parsing library for constrained decoding #1752 
- [x] Multi-layer radix cache (GPU/CPU/Disk) https://github.com/sgl-project/sglang/pull/2693  @xiezhq-hermann 
- [ ] Improve the performance of mixed chunked prefill. see a draft #1383 
- [ ] Integrate CuDNN paged attention [kernels](https://github.com/NVIDIA/cudnn-frontend/blob/v1.8.0/samples/python/52_scaled_dot_product_attention_with_paged_caches.ipynb) 

## Parallelism
- [ ] Support sequence parallelism #1436. Related [paper](https://www.arxiv.org/pdf/2411.01783)
- [ ] Support pipeline parallelism.
- [ ] Support expert parallelism + data parallelism for DeepSeek/MoE models. @ispobock 
    - [x] Data parallelism #1970 
    - [ ] Expert parallelism # #1435 
- [ ] Implement a better cache-aware load balancer for data parallelism. #2114 #1732 @ByronHsu @yichuan520030910320 
- [ ] Overlap communication in tensor parallelsim. @zhuohaol
- [ ] Support disaggregated serving to separate prefill and decoding.

## Hardware Coverage
- [ ] AMD optimizations. cc @HaiShaw 
  - CK kernels
  - Setup CI (accuracy/performance) for AMD
- [x] Intel XPU support.
  - #1480
  - #2121

## Model Coverage
- [x] Multi-modal models
  - Llama 3.2 Vision https://github.com/sgl-project/sglang/pull/1551
  - QWen2-VL https://github.com/sgl-project/sglang/pull/1546
  - DeepSeek VL2 https://github.com/sgl-project/sglang/issues/2653
  - mistralai/Pixtral https://github.com/sgl-project/sglang/issues/2351
  - GLM 4V https://github.com/sgl-project/sglang/pull/1641
  - VILA https://arxiv.org/abs/2412.04468
  - InternVL
  - Phi-vision
  - [FishSpeech](https://github.com/fishaudio/fish-speech) audio model support 
  - [Ultravox](https://github.com/sgl-project/sglang/issues/1271)
- [ ] Language models
  -  Mamba models @rahulbatra85 @HaiShaw 
  - xLSTM
- [x] Reward models
  - #1525 
  - #1954 

## New features
- [ ] Integrate with LMCache https://github.com/LMCache/LMCache
- [ ] A padded batch mode to make results more deterministic https://github.com/sgl-project/sglang/blob/8912b7637f5c8dca0f18c31a17e46f427cf53152/docs/references/faq.md?plain=1#L3
- [ ] Performance optimizations for multi-LoRA serving #1728 

## Quantization
@HaiShaw @zhyncs @ispobock 
- [x] Torchao integration #1561
- [ ] Turbomind operators integration
- [ ] More CUTLASS mixed precision gemm integration
- [ ] KV cache quantization (more formats + scaling factor)

## Server API
- [ ] Support directly taking embedding as inputs. #745
- [x] Add APIs for using the inference engine in a single script without launching a separate server. See also [examples](https://docs.vllm.ai/en/latest/getting_started/examples/offline_inference.html).
  - #1567
- [ ] Support endpoint other than OpenAI (Anthropic, Mistral) in the language frontend.
- [ ] Better APIs to support RL trainers, including https://github.com/huggingface/trl and https://github.com/OpenRLHF/OpenRLHF @zhaochenyang20 
- [ ] Support generalized reward API (adding linear layers to any Causal LM to get the reward) https://github.com/OpenRLHF/OpenRLHF @zhaochenyang20 

## Observability
- [x] Integrate Grafana / Prometheus
  - #1853  #1461 

## Others
- [x] Notebook-style interactive tutorials. @zhaochenyang20 
- [ ] Compiler mode optimizations for the language (e.g. support sending a full serialized SGL program to the server). @hnyls2002 
- [ ] Memory pool refactor to better support mixing different attention layers (e.g., interleaved window attention). @Ying1123 
- [ ] Make vLLM an optional dependency. @zhyncs @ByronHsu @yizhang2077 https://github.com/sgl-project/sglang/issues/1673

**Comment by fengyang95** [comment]
Are there any plans to optimize long context latency?

**Comment by lumiere-ml** [comment]
Hi，can I help for Multi-layer radix cache (GPU/CPU/Disk)？ Really insterested in that.

**Comment by tanzelin430** [comment]
> Are there any plans to optimize long context latency?

I am interested in contributing to P-D split inference architechure and I have machines that support me to develop the architechure, if you guys got any related develop plans please let me know. Thank you @Ying1123 @zhyncs @fengyang95

**Comment by merrymercy** [comment]
@lumiere-ml @tanzelin430 Are you in the slack channel? We can follow up on that.

**Comment by zhyncs** [comment]
> @lumiere-ml @tanzelin430 Are you in the slack channel? We can follow up on that.

@lumiere-ml @tanzelin430 Welcome to join our slack channel https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2ngly9muu-t37XiH87qvD~6rVBTkTEHw

**Comment by tanzelin430** [comment]
> > @lumiere-ml @tanzelin430 Are you in the slack channel? We can follow up on that.
> 
> @lumiere-ml @tanzelin430 Welcome to join our slack channel https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2ngly9muu-t37XiH87qvD~6rVBTkTEHw

thanks for invitation, I am in slack now. forward to collaberate with you

**Comment by lumiere-ml** [comment]
> > @lumiere-ml @tanzelin430 Are you in the slack channel? We can follow up on that.
> 
> @lumiere-ml @tanzelin430 Welcome to join our slack channel https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2ngly9muu-t37XiH87qvD~6rVBTkTEHw

Thanks for your invitation！

**Comment by Edenzzzz** [comment]
> > > @lumiere-ml @tanzelin430 Are you in the slack channel? We can follow up on that.
> > 
> > 
> > @lumiere-ml @tanzelin430 Welcome to join our slack channel https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2ngly9muu-t37XiH87qvD~6rVBTkTEHw
> 
> Thanks for your invitation！

@lumiere-ml @zhyncs I'm also very interested, could you share which channel you're using to discuss?
Perhaps we can combine radix tree prefix matching with P-D disaggregation similar to Mooncake?

**Comment by mfdj2002** [comment]
If no one is actively working on supporting pipeline parallelism, I'm down to help

**Comment by Edenzzzz** [comment]
@mfdj2002 I think @CalvinXKY has expressed interest on slack, you can chat with him there

**Comment by merrymercy** [comment]
No one is working on pipeline parallelism. Feel free to contribute one.

**Comment by m0g1cian** [comment]
I recently completed a reward model implementation for RMs trained by LlamaFactory. Everything worked well but I've noticed a relatively small value diff in last hidden states between my SGLang implementation and the counterpart in TRL (resulting a ROC loss of ~0.3%)

Regardless, I think I can help with the task "Support generalized reward API (adding linear layers to any Causal LM to get the reward)"

**Comment by kuangdao** [comment]
i  am interested in sequence parallelism, i want to know if the sequence parallelism will use the method of Context Parallelism for Scalable Million-Token Inference , thanks

**Comment by zhaochenyang20** [comment]
> I recently completed a reward model implementation for RMs trained by LlamaFactory. Everything worked well but I’ve noticed a relatively small value diff in last hidden states between my SGLang implementation and the counterpart in TRL (resulting a ROC loss of ~0.3%)
>
>
>
> Regardless, I think I can help with the task “Support generalized reward API (adding linear layers to any Causal LM to get the reward)”

Amazing, could you please send an Email with your wechat or other connection to zhaochenyang20@gmail.com

We can also discuss this on our Slack. find zhaochenyang20@gmail.com on sglang slack plz!

@m0g1cian

**Comment by trh11111** [comment]
I am also very interested in the scenario of PD disaggregation, and I hope to combine radix tree with PD disaggregation for some experiments. I saw that someone mentioned this in October. May I ask how the current development plan is progressing?

**Comment by zhaochenyang20** [comment]
> I am also very interested in the scenario of PD disaggregation, and I hope to combine radix tree with PD disaggregation for some experiments. I saw that someone mentioned this in October. May I ask how the current development plan is progressing?

@trh11111   Yeah. We have new members joined our team work on this and PD disaggregation is the first-priority in our developmap for  our next quoter.

**Comment by tanzelin430** [comment]
> I am also very interested in the scenario of PD disaggregation, and I hope to combine radix tree with PD disaggregation for some experiments. I saw that someone mentioned this in October. May I ask how the current development plan is progressing?

Hi, I have just finish my graduation recruiment senson and am working on my ATC paper. I'll be soon looking into the development

**Comment by zhaochenyang20** [comment]
> > I am also very interested in the scenario of PD disaggregation, and I hope to combine radix tree with PD disaggregation for some experiments. I saw that someone mentioned this in October. May I ask how the current development plan is progressing?
> 
> Hi, I have just finish my graduation recruiment senson and am working on my ATC paper. I'll be soon looking into the development

@trh11111 if you feel interested in this part, could reach out to us on slack.

**Comment by mpjlu** [comment]
> > @lumiere-ml @tanzelin430 Are you in the slack channel? We can follow up on that.
> 
> @lumiere-ml @tanzelin430 Welcome to join our slack channel https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2ngly9muu-t37XiH87qvD~6rVBTkTEHw

how to join this slack channel

**Comment by zhyncs** [comment]
Hi @mpjlu https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2rtikx2pv-DUfPrhx2SaNAq~47YtV1XQ

**Comment by mpjlu** [comment]
> Hi @mpjlu https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2rtikx2pv-DUfPrhx2SaNAq~47YtV1XQ

Thanks

**Comment by jjjjohnson** [comment]
@Ying1123  Reference-based speculative decoding #2790

**Comment by zhyncs** [comment]
This roadmap will be updated with Q1 2025 soon. Please stay tuned.

**Comment by GGKOP** [comment]
More CUTLASS mixed precision GEMM integration
KV cache quantization (more formats + scaling factor)
Can I help with these two parts? I need more requirements and details.

**Comment by zhyncs** [comment]
> More CUTLASS mixed precision GEMM integration KV cache quantization (more formats + scaling factor) Can I help with these two parts? I need more requirements and details.

Yeah https://github.com/sgl-project/sglang/tree/main/sgl-kernel/src/sgl-kernel/csrc
We currently support W8A8 Int8 and W8A8 FP8 using CUTLASS.

**Comment by GGKOP** [comment]
> > More CUTLASS mixed precision GEMM integration KV cache quantization (more formats + scaling factor) Can I help with these two parts? I need more requirements and details.
> 
> Yeah https://github.com/sgl-project/sglang/tree/main/sgl-kernel/src/sgl-kernel/csrc We currently support W8A8 Int8 and W8A8 FP8 using CUTLASS.

Hi, I spent some time figuring out parts of the code for FP8 GEMM and INT8 GEMM, but I didn't find any examples of applying W8A8. Did I miss something?

**Comment by zhyncs** [comment]
Hi all

The SGLang team has released the development roadmap for 2025 H1. Feel free to reach out if you want to collaborate or discuss.

Our main focus is on:

- Large-scale deployment focused on throughput, like the [DeepSeek inference system](https://github.com/deepseek-ai/open-infra-index?tab=readme-ov-file#day-6---one-more-thing-deepseek-v3r1-inference-system-overview)
- Optimizations for long contexts
- Speculative decoding with low latency
- Integration of reinforcement learning training framework
- Kernel optimizations

For more details, please refer to https://github.com/sgl-project/sglang/issues/4042 Cheers!
