### ISSUE TITLE
Development  Roadmap (2024 Q3)

### ISSUE THREAD

**Issue by Ying1123** [sgl-project/sglang#634]
Here is the development roadmap for 2024 Q3. Contributions and feedback are welcome.

## Server API
 - [ ] Add APIs for using the inference engine in a single script without launching a separate server. See also [examples](https://docs.vllm.ai/en/latest/getting_started/examples/offline_inference.html).
   - #1127 
 - [x] Support most OpenAI APIs: Batch, completion, chat, embedding
   - #699  
   - #640 
   - #852 
   - #916 
   - #997
- [ ] Support directly taking embedding as inputs. #745
- [x] Support updating the model weights without relaunching the server. @shanyu-sys 
   - #1157 
- [ ] Support Mistral endpoint in the language frontend
## Performance
- [x] Improve time-to-first-token in streaming mode with better scheduling.
  - #1339
  - #1345
- [x] Implement chunked prefill. @hnyls2002 @vikranth22446 
   - #800
   - #811 
   - #1040 
   - #1013 
- [ ] Implement speculative decoding. See also a [prototype](https://github.com/sgl-project/sglang/pull/270).
    - #859
## Parallelism
- [ ] Support sequence parallelism for long context models.
    - #1041
## Quantization
- [x] Support W8A16, W4A16 weight-only integer quantization. @zhyncs 
  - #1341 
- [ ] Support W4A8 quantization with fp8 activation and int4 weight.
- [x] Support fp8/fp4 KV cache quantization. int4/int8 is low priority. Currently we've supported fp8 e5m2, and we should also support fp8 e4m3. @ispobock 
  - #1204
## Observability
- [ ] Integrate Grafana / Prometheus
  - #1461 
## Model Coverage
- [x] Support interleaved window attention (gemma). @Ying1123 
  - #1056 
  - #1090 
  - #1112 
  - #1151 (delayed to Q4, which is dependent on new memory manager)
- Language Models
  - [ ] Mamba models
  - [x] Deepseek models
     - #689 
     - #693 
     - #905 
     - #1138
     - #1285
- Vision Language Models
  - [x] [LLaVA-OneVision](https://llava-vl.github.io/blog/2024-08-05-llava-onevision/)
    - #1123  
  - [ ] [CogVLM2](https://github.com/THUDM/CogVLM2)
  - [ ] [Cambrian-1](https://cambrian-mllm.github.io/)
  - [ ] Phi-vision
- [x] Embedding models
  - #983 
  - #987 
  - #988 
  - #997 
  - #1014 
  - #1186 
## Hardware Coverage
- [x] AMD support
  - #1420
## Language API
- [ ] Function calling. Add `tools` argument in `sgl.gen`. See also [guidance](https://github.com/guidance-ai/guidance/blob/d1bbe1c698cbb201f89556d71193993e78c0686b/README.md?plain=1#L102) and [Claudette](https://www.answer.ai/posts/2024-06-21-claudette.html). For OpenAI models, we can translate to their function calling API (https://platform.openai.com/docs/guides/function-calling). For local models, we can use SGLang primitives (regex, select) and constrained decoding to implement a similar workflow. Or we can interrupt the decoding process to replace it with function callings. @Yiyun-Liang 
  - #573 
- [ ] Support sending a full serialized SGL program to the server.
- [x] Constraint decoding
  - #1125 
## LoRA Support
- [x] Port multi-LoRA serving from [S-LoRA](https://github.com/S-LoRA/S-LoRA) (Full optimizations will be in Q4 planning). @Ying1123 
  - #1307 
  - #1433 
## Usage examples
- [ ] Add more usage examples (e.g., [parallel JSON decoding](https://github.com/varunshenoy/super-json-mode/issues/8), [auto parallel decoding](https://arxiv.org/abs/2401.06761), [Self-Discover: Large Language Models Self-Compose Reasoning Structures](https://arxiv.org/abs/2402.03620)).
## Others
- [x] Setup CI. @zhyncs @hnyls2002 @merrymercy @Ying1123 
- [x] Documentation website.
- Compiler mode optimizations for the language. (Delayed to Q4)

**Comment by zhyncs** [comment]
> Support W8A4 quantization with fp8 activation and int4 weight.

typo: W8A4 -> W4A8

**Comment by Ying1123** [comment]
> > Support W8A4 quantization with fp8 activation and int4 weight.
> 
> typo: W8A4 -> W4A8

Thanks! Changed.

**Comment by LinqingZhong** [comment]
May I ask if there is an example for using llava-next-interleave with multi images ?

**Comment by anatoli26** [comment]
I guess ROCm support is under Hardware Coverage - AMD support. Any ETA for this?

**Comment by usaxena-asapp** [comment]
Hey @Ying1123 - are you okay with open source contributions from developers outside the core team? Looking to find more places I can contribute and I'm excited about SGLang. Just wondering.

**Comment by Ying1123** [comment]
> Hey @Ying1123 - are you okay with open source contributions from developers outside the core team? Looking to find more places I can contribute and I'm excited about SGLang. Just wondering.

Hi @usaxena-asapp, definitely! There is no strict definition of a "core team," and I'm just a volunteer to coordinate. If you contribute a lot, you are a core member! Let me know if you need any help from people with experience. My suggestion is to start with small issues and PRs and join discussions. If you want to start a big one, you can start with a simple proposal to trigger collaborations from the community.

**Comment by Ying1123** [comment]
> I guess ROCm support is under Hardware Coverage - AMD support. Any ETA for this?

Hi @usaxena-asapp, thanks for the question, we list it in the roadmap, but we might just start with some basic tests. Optimizations will depend on how many people and resources we can get.

**Comment by anatoli26** [comment]
> we list it in the roadmap, but we might just start with some basic tests. Optimizations will depend on how many people and resources we can get.

Have you tried talking to AMD for hardware samples (e.g. a pair of W7900) and software collaboration? They are trying hard to be on par with NVIDIA in software stack: [AMD is Becoming a Software Company. Here's the Plan](https://www.techpowerup.com/324171/amd-is-becoming-a-software-company-heres-the-plan). The author of the article has some great connections with the AMD people, maybe you could write him (W1zzard under the title) to ask for contacts at AMD responsible for relations with FOSS projects?

**Comment by ghchris2021** [comment]
IDK if there's any potential interest to broaden the concepts involved in "Hardware Coverage" but in case it may raise some ideas to consider in the future:

You mention CPU support, AMD support, but there are higher level frameworks that MAY considerably help with supporting different hardware backends (CPU, GPU) so you don't necessarily have to put as much work / focus into supporting a SPECIFIC backend -- they may ease / largely solve running on more than one for the same effort.  
For instance OpenCL, SYCL, Vulkan compute, maybe OpenACC, and others are somewhat portable parallel computing frameworks and support some CPU(s) and some GPU(s) typically at least a couple if not several.

IIRC OpenCL can run on Nvidia, Amd, Intel GPUs as well as Intel & AMD & I  think some ARM CPUs.

IIRC SYCL runs on Intel GPUs, Intel / AMD CPUs, and I believe also NVIDIA GPUs.  It may run on AMD GPUs but I'm not so sure about that.

There are higher level still frameworks / implementations that can encapsulate / provide some of the tools / implementations for such open standards e.g. 

https://github.com/AdaptiveCpp/AdaptiveCpp

targets SYCL but also provides C++ std:: paralellism programming models.  

POCL, RustiCL, and several other (intel, amd, nvidia, ...) development packages / solutions support particular instances of platforms with functional compatible OpenCL support.

Besides the NVIDIA, AMD GPUs Intel has generations of data center / enterprise / business / consumer grade GPUs which are strong in their capabilities and they've got the same tooling / documentation / etc. across the product line insofar as supporting stuff like SYCL, OneAPI, OpenVINO, DPC++, libraries like OneDNN, etc. etc. for GPU families and CPUs.

There exist vulkan wrappers and higher level middleware that encapsulate the details of Vulkan compute programming and expose easier to use developer interfaces / solutions for general parallel compute, math / arithmetic / matrix / vector / NN etc. stuff.  

IIRC all major gpus NVIDIA / AMD / Intel have Vulkan compatible runtimes and development options available and several ARM SOC etc. GPUs as well.  So it as a middleware layer could help support numerous platforms for a single quantum of effort to target Vulkan based operations for the primary memory / NN / linear algebra etc. related calculations that can be accelerated.

So I'm just suggesting trying to reach for tools to support multiple standards based platforms if that eases your work and also broadens / accelerates the support of more platforms.

**Comment by CSEEduanyu** [comment]
https://github.com/sgl-project/sglang/pull/270/commits

**Comment by CSEEduanyu** [comment]
I noticed that the speculate decode function has been implemented in the branch https://github.com/sgl-project/sglang/pull/270/commits, why was this commit closed? How long will it take to support speculate decode? Thank you for your reply.

**Comment by TimDettmers** [comment]
This is an awesome project! Thank you for this. @Ying1123 I am interested in using SGLang for multi-LoRA deployments for a project. The alternative is currently vLLM, but I like SGLang better. I am curious about the current state and timeline for supporting S-LoRA-like deployment.

**Comment by Ying1123** [comment]
> This is an awesome project! Thank you for this. @Ying1123 I am interested in using SGLang for multi-LoRA deployments for a project. The alternative is currently vLLM, but I like SGLang better. I am curious about the current state and timeline for supporting S-LoRA-like deployment.

Hi @TimDettmers, happy to hear from you! I got the same request from another SGLang user, so I am actively working on the multi-LoRA module, which is expected to have a first runnable version in a week. You are welcome to join our [Slack](https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2nsybupkx-oEQ8vMxFkMOC0d5ECB_A2A) and send me your sample script!

**Comment by hxer7963** [comment]
Have no plan to support W8A8 quantization?

**Comment by brotherchen** [comment]
Can the current excellent performance (compared to vllm) be understood as excellent engineering implementation (such as using multiple processes to reduce CPU overhead) and more efficient scheduling strategies? And I want to know whether support for pipeline parallelism is being considered.

**Comment by merrymercy** [comment]
@hxer7963 fp8 W8A8 quantization is supported.

@brotherchen yes. Pipeline parallelism will be in the plan of Q4

**Comment by CedricHwong** [comment]
Planning to use Sglang on Intel Gaudi 2, but I have not tried it yet. Would like to know the current support level？

**Comment by mingfeima** [comment]
> Planning to use Sglang on Intel Gaudi 2, but I have not tried it yet. Would like to know the current support level？

@xinyu-intel we don't have binding for Gaudi 2 yet, right?

**Comment by xinyu-intel** [comment]
@CedricHwong @mingfeima Hi, glad to see the requests for sglang on Intel Gaudi. Currently, it's not implemented and we are evaluating the feasibility.

**Comment by zhyncs** [comment]
Most of the list in this 2024 Q3 roadmap has been completed, and the unfinished parts have been migrated to the 2024 Q4 roadmap. This issue is now closed. For those interested in the latest roadmap, please follow https://github.com/sgl-project/sglang/issues/1487
